name: Publish Docs
on:
  push:
    branches:
      - master
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    name: Docs builder and publisher
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install sphinx sphinx-rtd-theme sphinx-inline-tabs matplotlib
      - name: Install Gdstk
        run: python setup.py install --user
      - name: Make figures and samples
        run: |
          python docs/cell_images.py
          python docs/curve_images.py
          python docs/flexpath_images.py
          python docs/function_images.py
          python docs/label_images.py
          python docs/polygon_images.py
          python docs/reference_images.py
          python docs/robustpath_images.py
          python docs/tutorial_images.py
          python docs/pcell.py
          python docs/photonics.py
          python docs/layout.py
          python docs/merging.py
          python docs/transforms.py
          python docs/repetitions.py
          python docs/apply_repetition.py
          python docs/filtering.py
          python docs/pos_filtering.py
          python docs/path_markers.py
          python docs/fonts.py
      - name: Build docs
        run: python setup.py build_sphinx
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          publish_branch: gh-pages
          keep_files: false
          force_orphan: true

